import "./tailwind.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <nav className="flex p-4 border-b">
          <h1 className="text-4xl uppercase bold">cvcreaLogo</h1>
          
        </nav>
        {children}
      </body>
    </html>
  );
}
